name: Testana
favicon: null
layout_spectrum: 0.7232917072251439
typography_spectrum: 0.6535080063622445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.669618614949286
  lightness: 0.08815921493805945
  saturation: 0.9521160260774195
  rhythmicContrast: 0.7965077618137002
purpose: []
